---
title: "README"
author: "JAE Finger"
date: "12/9/2018"
output: html_document
---
#Getting and Cleaning Data Peer Project README

###The goal of this project is to:
* Merge the training and the test sets to create one data set.  
* Extract only the measurements on the mean and standard deviation for each measurement.  
* Use descriptive activity names to name the activities in the data set  
* Appropriately label the data set with descriptive variable names.  
* From the data set in step 4, create a second, independent tidy data set with the average of each variable for each activity and each subject.  
  
As such, the `run_analysis.R` script accomplishes this goal. 

###This script:
1. Downloads the training and test data, and unzips the file  
2. Imports the pertinent data files  
3. Merges the datasets  
4. Grabs the mean and standard deviations for each measurement  
5. Fixes the activity names and describes varibles  
6. Creates a new text file called tidy_data.txt  

  
This repository includes this `README.rmd`, a `run_analysis.R` script, and a `CodeBook.rmd`